config/routes.rb
 Rails.application.routes.draw do


  resources :photos
  devise_for :users,
     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  root to: 'pages#home'

  resources :own_contents do
    member do
      put "like" => "own_contents#like"
    end
    resources :own_content_comments, only: [:index, :new, :create, :show]
    resources :favourites, only: [:new, :create,:destroy]
  end


  resources :education_contents do
    member do
      put "like" => "education_contents#like"
    end
  end

  resources :didyouknows do
  end

 get '/library', to: 'pages#library'
 get '/newsfeed', to: 'pages#newsfeed'
 get '/favourites', to: 'favourites#index'
 get '/about', to: 'pages#about'
 get '/faq', to: 'pages#faq'


  resources :users, only: [:show, :edit, :update]
      # post "users/:id", to: "users#show"
      # get "users/:id/edit", to: "users#edit"
      # patch "users/:id", to: "users#update"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/own_content.rb
class OwnContent < ApplicationRecord
  has_many :own_content_comments
  has_many :favourites, dependent: :destroy
  has_one_attached :photo
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :category, presence: true
  validates :description, presence: true
  validates :published_date, presence: true
  validates :reading_time, presence: true
  validates :photo, presence: true
  validates :article, presence: true

  acts_as_votable

  searchkick #:text_middle [:title]

  def search_data
    {
      title: title,
    }
  end
end

app/controllers/own_contents_controller.rb
class OwnContentsController < ApplicationController

  before_action :find_content, only: [:show, :like, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :like]

  respond_to :js, :html, :json

  def index
    @own_contents = policy_scope(OwnContent)
  end

  def show
    # find_content
    @own_content_comment = OwnContentComment.new
  end

  def new
    @own_content = OwnContent.new
    authorize @own_content
  end

  def create
    @own_content = OwnContent.new(owncontent_params)
    @own_content.user = current_user
    authorize @own_content
    if @own_content.save
      redirect_to library_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @own_content.update(owncontent_params)
    redirect_to own_content_path(@own_content), alert: "Article Updated"
  end

  def destroy
   @own_content.destroy
   redirect_to library_path, alert: "Article Deleted"
  end

  def like
    if current_user.voted_for? @own_content
      @own_content.unliked_by current_user
    else
      @own_content.liked_by current_user
    end
  end

  private

  def find_content
    @own_content = OwnContent.find(params[:id])
    authorize @own_content
  end

  def owncontent_params
    params.require(:own_content).permit(:title, :description, :article, :category, :published_date, :photo, :reading_time)
  end
end

app/views/own_contents/_like_link.html.erb
<% vote_text = current_user&.voted_for?(own_content) ? "👎" : "👍" %>

<%= link_to vote_text, like_own_content_path(own_content), method: :put, remote: :true, class: 'like-link' %>

app/views/own_contents/_likes.html.erb
<%= "#{own_content.get_upvotes.size}" %>

app/views/own_contents/edit.html.erb
  <div class="primary-container-newsfeed">
  <div class="row">
    <div class="col">
      <h5> Hello <%= current_user.first_name %>, edit your article below </h5>
      <br>
      <hr></hr>
      <%= simple_form_for @own_content do |f| %>
      <%= f.input :title %>
      <%= f.input :reading_time %>

      <label>Key Take Away</label>
      <%= f.input :description, as: :hidden, :input_html => { :id => "key_take_away" } %>
      <trix-editor input="key_take_away"></trix-editor>
      <br>

      <%= f.input :photo, as: :file %>

      <label>Content</label>
      <%= f.input :article, as: :hidden, :input_html => { :id => "article_content" } %>
      <trix-editor input="article_content"></trix-editor>
      <br>

      <%= f.input :category, collection: [ "Bitcoin", "Ethereum", "Cryptocurrency", "Breaking News", "Finance", "Technology", "Other"] %>
      <%= f.input :published_date, as: :datetime %>
      <%= f.button :submit, "Update article", class: "btn-login-sign-up-gradient" %>
      <% end %>
      <br><br>
    </div>
  </div>
 </div>

app/views/own_contents/like.js.erb
$(".like-count").html("<%= j render 'own_contents/likes', own_content: @own_content %>");
$(".like-link").html("<%= j render 'own_contents/like_link', own_content: @own_content %>");

app/views/own_contents/new.html.erb
<div class="primary-container-newsfeed">
  <div class="row">
    <div class="col">
      <h5> Hello <%= current_user.first_name %>, create your article below </h5>
      <br>
      <hr></hr>
      <%= simple_form_for @own_content do |f| %>
      <%= f.input :title %>
      <%= f.input :reading_time %>

      <label>Key Take Away</label>
      <%= f.input :description, as: :hidden, :input_html => { :id => "key_take_away" } %>
      <trix-editor input="key_take_away"></trix-editor>
      <br>

      <%= f.input :photo, as: :file %>

      <label>Content</label>
      <%= f.input :article, as: :hidden, :input_html => { :id => "article_content" } %>
      <trix-editor input="article_content"></trix-editor>
      <br>

      <%= f.input :category, collection: [ "Bitcoin", "Ethereum", "Cryptocurrency", "Breaking News", "Finance", "Technology", "Other"] %>
      <%= f.input :published_date, as: :datetime %>
      <%= f.button :submit, "Publish your article", class: "btn-login-sign-up-gradient" %>
      <% end %>
      <br><br>
    </div>
  </div>
 </div>

app/views/own_contents/show.html.erb
<% content_for :meta_title, "#{sanitize @own_content.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "#{sanitize @own_content.description, tags: %w()}" %>
<% if @own_content.photo.attached? %>
  <% content_for :meta_image, cl_image_path(@own_content.photo.key) %>
<% else %>
  <%= content_for :meta_image, "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80" %>
<% end %>

<!-- Article thumbnail -->
<div class="article_banner">
  <% if @own_content.photo.attached? %>
    <div class="article_thumbnail" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @own_content.photo.key %>')">
      <%= render 'components/banner_owncontent' %>
    </div>

  <% else %>
    <div class="article_thumbnail" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1518546305927-5a555bb7020d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80')">
      <%= render 'components/banner_owncontent' %>
    </div>
  <% end %>
</div>

<div class="primary-container">

  <!-- Article icons -->
  <div class="article_icons">
    <!-- like button -->
    <div class="likes">
      <div class="like-count">
        <%= render 'own_contents/likes', own_content: @own_content %>
      </div>

      <div class="like-link">
        <%= render 'own_contents/like_link', own_content: @own_content %>
      </div>
    </div>

    <!-- social-share-button -->
    <div class="social-share-btn-article">

      <!-- To include Twitter hashtags copy+paste "&hashtags={hash_tags}" to the end of href and replace "{hash_tags}" -->
      <a class="twitter-link" href="https://twitter.com/intent/tweet?url=<%= request.original_url %>&text=<%= "#{@own_content.title}" %>+&via=finmates_co" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=240,width=600');return false;">
        <i class="fab fa-twitter-square"></i>
      </a>

      <a href="https://www.facebook.com/dialog/share?app_id=307358133764324&display=popup&href=<%= request.original_url %>&redirect_uri=<%= request.original_url %>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=240,width=600');return false;">
        <i id="shareBtn" class="fab fa-facebook-square"></i>
      </a>

      <a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<%= request.original_url %>&amp;title=<%= "#{@own_content.title}" %>&amp;source=finmates.co" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=240,width=600');return false;">
        <i class="fab fa-linkedin"></i>
      </a>

    </div>
  </div>
  <br>
  <!-- Article abstract -->
  <div class="article_abstract">
    <p><%= sanitize @own_content.description %></p>
  </div>

  <!-- Article content -->
  <div class="article_content">
    <% if user_signed_in? %>
      <p><%= sanitize @own_content.article %></p>
    <% else %>
      <div class="blurry-paywall">
        <p><%= sanitize @own_content.article.truncate_words(50, seperator: /\s/) %></p>
      </div>
      <div class="read-full-story">
        <p><strong>TO READ THE FULL STORY</strong></p>
      </div>
      <div class="flex-sign-up-login-btn">
        <%= link_to "Sign up", new_user_registration_path, class: "btn-horizontal-gradient" %>
        <%= link_to "Log in", new_user_session_path, class: "btn-horizontal-white" %>
      </div>
    <% end %>
  </div>

  <!-- Comments -->
  <div class="comments-title">
    <h2>Comments</h2>
  </div>

  <%= simple_form_for [ @own_content, @own_content_comment ], html: { id: :comment_form }, remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Comment on ##{@own_content.title}", :input_html => { :id => "enter_submit" } %>
    <div class="comment-submit">
      <%= f.submit "Post", class: "btn-comment" %>
    </div>
  <% end %>

  <div id="own_content_comments" data-own_content-id="<%= @own_content.id %>">
    <% @own_content.own_content_comments.each do |own_content_comment| %>
      <%= render 'own_content_comments/own_content_comment', own_content_comment: own_content_comment %>
    <% end %>
  <br><br>
  </div>
</div>