config/routes.rb
 Rails.application.routes.draw do


  resources :photos
  devise_for :users,
     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  root to: 'pages#home'

  resources :own_contents do
    member do
      put "like" => "own_contents#like"
    end
    resources :own_content_comments, only: [:index, :new, :create, :show]
    resources :favourites, only: [:new, :create,:destroy]
  end


  resources :education_contents do
    member do
      put "like" => "education_contents#like"
    end
  end

  resources :didyouknows do
  end

 get '/library', to: 'pages#library'
 get '/newsfeed', to: 'pages#newsfeed'
 get '/favourites', to: 'favourites#index'
 get '/about', to: 'pages#about'
 get '/faq', to: 'pages#faq'


  resources :users, only: [:show, :edit, :update]
      # post "users/:id", to: "users#show"
      # get "users/:id/edit", to: "users#edit"
      # patch "users/:id", to: "users#update"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_avatar_modal.html.erb
<div class="modal fade" id="avatarModal" tabindex="-1" role="dialog" aria-labelledby="avatarModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="avatarModalTitle">Edit Profile Picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="forms-container">
                  <%= simple_form_for @user, method: :patch do |f| %>
                    <%= f.input :avatar, as: :file, label: false %>

                    <%= f.button :submit, "Upload", class: "btn-gradient" %>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="primary-container">

    <div class="footer-links">
      <a target="_blank" href="https://www.privacypolicygenerator.info/live.php?token=yZEnESzSnmfsHnHiyqex1sIOqOUXqNnz">Privacy Policy</a>
      <p><%= link_to "FAQs", faq_path %></p>
      <p><%= link_to "About Us", about_path %></p>
    </div>

    <br><br>

    <div class="social-share-btn">
      <!-- To include Twitter hashtags copy+paste "&hashtags={hash_tags}" to the end of href and replace "{hash_tags}" -->
      <a class="footer-facebook" href="https://www.facebook.com/Finmates-103276188141186/" target="_blank">
        <i id="shareBtn" class="fab fa-facebook-square"></i>
      </a>

      <a class="footer-twitter" href="https://twitter.com/finmates_co" target="_blank">
        <i class="fab fa-twitter-square"></i>
      </a>

      <a class="footer-linkedin" href="https://www.linkedin.com/company/finmates-co" target="_blank">
        <i class="fab fa-linkedin"></i>
      </a>

      <a href="mailto:finmatesapp@gmail.com" target="_blank">
        <i class="fas fa-envelope-square"></i>
      </a>
    </div>

    <br>

    <div class="copyright">
      <p>© 2020 Finmates.</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav navbar fixed-top mb-3">

  <!-- Finmates Logo -->
  <div class="fmlogo">
    <%= link_to image_tag('fm_heading.png'), newsfeed_path %>
  </div>

    <div class="burger">
      <div class="line1"></div>
      <div class="line2"></div>
      <div class="line3"></div>
    </div>

    <!-- SIGNED IN - Burger Menu -->
    <% if user_signed_in? %>
      <div class="nav-links">
        <ul class="navbar-menu">
          <li class="menu-item">
            <a id="newsfeed" href="<%= newsfeed_path %>"><%= image_tag('news-text.png') %>Newsfeed</a>
          </li>
          <li class="menu-item">
            <a id="library" href="<%= library_path %>"><%= image_tag('content-text.png') %>Library</a>
          </li>
          <li class="menu-item">
            <a id="favourites" href="<%= favourites_path %>"><%= image_tag('microphone-alt-solid.png') %>Podcasts</a>
          </li>
          <li class="menu-item">
            <a id="<%= current_user.id %>" href="<%= user_path(current_user.id) %>"><%= image_tag('profile-text.png') %>Profile</a>
          </li>
          <% if current_user.admin %>
            <li class="menu-item">
              <a id="new" href="<%= new_own_content_path %>"><%= image_tag('add_box_24px.png') %>Add Content</a>
            </li>
          <% end %>
        </ul>
      </div>

    <!-- NOT SIGNED IN - Burger Menu Image -->
    <% else %>
      <div class="nav-links">
        <ul class="navbar-menu">
          <li class="menu-item">
            <a id="newsfeed" href="<%= newsfeed_path %>"><%= image_tag('news-text.png') %>Newsfeed</a>
          </li>
          <li class="menu-item">
            <a id="library" href="<%= library_path %>"><%= image_tag('content-text.png') %>Library</a>
          </li>
          <li class="menu-item">
            <a id="log-in" href="<%= new_user_session_path %>"><%= image_tag('sign-in-alt-solid.png') %>Log In</a>
          </li>
          <li class="menu-item">
            <a id="sign-up" href="<%= new_user_registration_path %>"><%= image_tag('sign-up-solid.png') %>Sign Up</a>
          </li>
        </ul>
      </div>
  <% end %>
</div>

<!-- JS - Nav Menu Slide -->
<script>
   const navSlide = () => {
      const burger = document.querySelector('.burger');
      const nav = document.querySelector('.nav-links');
      const navLinks = document.querySelectorAll('.nav-links li');

      burger.addEventListener('click', () => {
        // Toggle Nav
        nav.classList.toggle('nav-active');

      //Animate Links
      navLinks.forEach((link, index) => {
        if (link.style.animation) {
            link.style.animation = '';
        } else {
          link.style.animation = `navLinkFade 0.5s ease forwards ${index / 7 + 0.5}s`;
        }
      });
      //Burger Animation
      burger.classList.toggle('cross');
    });
  }

  navSlide ();
 </script>