config/routes.rb
 Rails.application.routes.draw do


  resources :photos
  devise_for :users,
     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  root to: 'pages#home'

  resources :own_contents do
    member do
      put "like" => "own_contents#like"
    end
    resources :own_content_comments, only: [:index, :new, :create, :show]
    resources :favourites, only: [:new, :create,:destroy]
  end


  resources :education_contents do
    member do
      put "like" => "education_contents#like"
    end
  end

  resources :didyouknows do
  end

 get '/library', to: 'pages#library'
 get '/newsfeed', to: 'pages#newsfeed'
 get '/favourites', to: 'favourites#index'
 get '/about', to: 'pages#about'
 get '/faq', to: 'pages#faq'


  resources :users, only: [:show, :edit, :update]
      # post "users/:id", to: "users#show"
      # get "users/:id/edit", to: "users#edit"
      # patch "users/:id", to: "users#update"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
  <!-- OUR-STORY-SECTION -->
    <div class="primary-container">
      <div class="our-story" id="our-story">

     <!-- BACK TO ROOT BTN -->
      <h1><%= link_to "<", :back, class: "banner-icons mt-3 pt-5" %></h1>
      <br>

          <h2>Our Story</h2>

            <br>

          <p>Finmates' vision is to become the Bloomberg for millennials, providing digestible news and education pieces to make sound investment decisions 💸📈. <br><br>

          At Finmates, we are incredibly driven & passionate about making financial information more accessible to all. According to a survey conducted by Investopedia and Pew Research Center, only 37% of millennials feel knowledgeable about investing at all. This percentage drops down even further when it comes to cryptocurrency. We want to tackle that by introducing Finmates to the market 🤩. <br><br>

          At launch, Finmates will purely focus on crypto insights as we see the trend shifting to a digital and decentralized financial environment. You’ve probably heard or read about cryptocurrencies, and blockchains, and all kinds of terms in that space. But do you really understand what’s going on? And if so, can you actually see through the jungle of all the different platforms, podcasts, tweets, YouTube channels, etc.❓ <br><br>

          Don’t get us wrong, we are no experts on this matter! It's frustrating to see the lack of easy-to-understand resources on cryptocurrency. We want to build a community that shares information and knowledge as members try to navigate the crypto world! 🕵 <br><br>

          That said, we dare to envisage to be your one-stop-shop for information, updates, and, of course, fun stuff surrounding cryptocurrencies. Much like ALDI might be your one-stop grocery shop, we’d like to build an independent platform, where you happily shop for your crypto insights 🛍 🛒. <br><br>

          The first step on our self-imposed mission is to build and develop this cool app to help others – and ourselves – understand what is happening in this “new” and "crazy" world of crypto by providing bite-sized snacks for your consumption 🍿, without all the complicated, fancy words 🙅. <br><br>

          Eventually, we hope to excite others about cryptocurrencies and all that it may entail. We hope you jump on board 🚀.</p>

      </div>
    </div>

app/views/pages/faq.html.erb
<!-- FAQ-SECTION -->
    <div class="primary-container">
      <div class="our-story" id="our-story">

        <!-- BACK TO ROOT BTN -->
        <h1><%= link_to "<", :back, class: "banner-icons mt-3 pt-5" %></h1>

        <br>

            <h2>FAQs</h2>
              <br>
            <p>

              <strong>What is Finmates?</strong>

              <br>

              Finmates is a user-friendly focused platform to help navigate the confusing world of Bitcoin and cryptocurrencies. <br><br>We aim to simplify and educate the novice-investor, while keeping the traditional investor updated on all the important happenings in the cryptocurrency space.

              <br><br><br>


              <strong>How does Finmates work?</strong>

              <br>

              Our main focus is Bitcoin and Ethereum, while covering other important areas such as regulation and adoption. <br><br>We aim to achieve this through a subscription-based model, providing regular updates on our platform.

              <br><br><br>

              <strong>What problem is Finmates aiming to solve?</strong>

              <br>

              We want to provide education for users to help evolve the cryptocurrency space towards mainstream adoption.

              <br><br><br>


              <strong>What is Finmates’ vision?</strong>

              <br>

              Our vision is to be a reliable and constant source of information for users from all experience levels. We aim to facilitate the growth of this technological innovation through education towards mainstream adoption.

              <br><br><br>


              <strong>How does Finmates help the cryptocurrency space?</strong>

              <br>

              We aim to achieve the breakdown of this technological innovation through simplified education. We want to fill the knowledge gap required for those looking to invest and grow their knowledge.

              <br><br><br>


              <strong>When can I sign up?</strong>

              <br>

              We are currently live and users can sign up at finmates.co!

              <br><br><br>

            </p>

      </div>
    </div>

app/views/pages/home.html.erb
<div id="lp-top">

<!-- BANNER -->
  <section id="banner">
    <div class="banner">
      <div class="banner-content">

        <div class="lp-links">
          <%= link_to "Our story | ", '#our-story'%>
          <%= link_to "What we provide | ", '#what-we-provide'%>
          <%= link_to "Benefits | ", '#your-benefits'%>
          <%= link_to "Who are we", '#who-are-we'%>
        </div>

          <div class="banner-slogan">
            <h1>  Your one-stop-shop for the latest crypto insights to...  <br><div id="typing" class="typing"></div></h1>
          </div>

          <%= link_to newsfeed_path do %>
            <button class="btn-white"> Go to Newsfeed </button>
          <% end %>
        </div>

          <div class="mx-3 mt-5 pt-3 head">
            <h5>Check out the latest articles on Finmates 🗞</h5>
         </div>
          <div class="cardsnf mx-3 py-4">
            <% @top_content.each do |own_content| %>
                <%= link_to own_content_path(own_content) do %>
                  <%= render 'components/card', own_content: own_content %>
                  <br>
                <% end %>
            <% end %>
          </div>
      </div>
  </section>


  <!-- OUR-STORY-SECTION -->
    <div class="primary-container">
      <div class="our-story" id="our-story">
        <h2>Our Story</h2>

        <p>Finmates' vision is to become the Bloomberg for millennials, providing digestible news and education pieces to make sound investment decisions 💸📈. <br><br>

        At Finmates, we are incredibly driven & passionate about making financial information more accessible to all. According to a survey conducted by Investopedia and Pew Research Center, only 37% of millennials feel knowledgeable about investing at all. This percentage drops down even further when it comes to cryptocurrency. We want to tackle that by introducing Finmates to the market 🤩. <br><br>

        At launch, Finmates will purely focus on crypto insights as we see the trend shifting to a digital and decentralized financial environment. You’ve probably heard or read about cryptocurrencies, and blockchains, and all kinds of terms in that space. But do you really understand what’s going on? And if so, can you actually see through the jungle of all the different platforms, podcasts, tweets, YouTube channels, etc.❓ <br><br>

        Don’t get us wrong, we are no experts on this matter! It's frustrating to see the lack of easy-to-understand resources on cryptocurrency. We want to build a community that shares information and knowledge as members try to navigate the crypto world! 🕵 <br><br>

        That said, we dare to envisage to be your one-stop-shop for information, updates, and, of course, fun stuff surrounding cryptocurrencies. Much like ALDI might be your one-stop grocery shop, we’d like to build an independent platform, where you happily shop for your crypto insights 🛍 🛒. <br><br>

        The first step on our self-imposed mission is to build and develop this cool app to help others – and ourselves – understand what is happening in this “new” and "crazy" world of crypto by providing bite-sized snacks for your consumption 🍿, without all the complicated, fancy words 🙅. <br><br>

        Eventually, we hope to excite others about cryptocurrencies and all that it may entail. We hope you jump on board 🚀.</p>

      </div>
    </div>

  <!-- WHAT-WE-PROVIDE-SECTION -->
  <section id="what-we-provide">

    <div class="primary-container">

      <div class="what-we-provide-header">
        <h2>What we provide</h2>
      </div>

      <!-- 1. Feature -->
      <div class="what-we-provide">
        <div class="text-1">
          <h3>1. Educational Content</h3>
          <p>Easy to understand introduction into the world of cryptocurrencies with brief, simplified information</p>
        </div>

        <div class="iphone-1">
          <%= image_tag('education.png') %>
        </div>
      </div>

      <!-- 2. Feature -->
      <div class="what-we-provide">
        <div class="iphone-2">
          <%= image_tag('original-content.png') %>
        </div>

        <div class="text-2">
          <h3>2. Original articles & audio</h3>
          <p>YOLO! Bitcoin and blockchin news summarised for easy consumption</p>
        </div>
      </div>

      <!-- 3. Feature -->
      <div class="what-we-provide">
        <div class="text-3">
          <h3>3. Social media </h3>
          <p> Twitter can get noisy, we will only provide you with the most relevant content </p>
        </div>

        <div class="iphone-3">
          <%= image_tag('social-media.png') %>
        </div>
      </div>

    </div>
  </section>

  <!-- YOUR BENEFITS -->
  <section id="your-benefits">


    <div class="primary-container">
      <div class="benefits-container">

        <div class="benefits-content">

          <div class="benefit-1">
            <div class="icon-1">
              <i class="fas fa-shipping-fast"></i>
            </div>
            <div class="benefit-text-1">
              <h5>Bite-sized Insights</h5>
              <p>Get up-to-date quickly with our regular insights</p>
            </div>
          </div>

          <div class="benefit-2">
            <div class="icon-2">
              <i class="fas fa-comment-slash"></i>
            </div>
            <div class="benefit-text-2">
              <h5>No fancy words</h5>
              <p>Enjoy crypto news that is easy to understand - without jargon</p>
            </div>
          </div>

          <div class="benefit-3">
            <div class="icon-3">
              <i class="fas fa-exclamation-triangle"></i>
            </div>
            <div class="benefit-text-3">
              <h5>Only important stuff</h5>
              <p>Filter through the junk</p>
            </div>
          </div>
        </div>

        <div class="benefits-silver-platter">
          <%= image_tag('your-benefits-silver-platter.png') %>
        </div>

      </div>
    </div>
  </section>

  <!-- WHO-ARE-WE -->
  <section id="who-are-we">
    <div class="who-are-we-header">
      <h2>Who are we?</h2>
    </div>

    <div class="who-are-we-container">

      <div class="who-are-we-card-1">
        <div class="who-are-we-photo">
          <%= image_tag('earl.png') %>
        </div>
        <p>Earl Quinlan</p>
      </div>

      <div class="who-are-we-card-2">
        <div class="who-are-we-photo">
          <%= image_tag('prateek.png') %>
        </div>
        <p>Prateek Mahindra</p>
      </div>

      <div class="who-are-we-card-3">
        <div class="who-are-we-photo">
          <%= image_tag('tim-new.png') %>
        </div>
        <p>Tim Vierboom</p>
      </div>
    </div>

    <div class="arrow-up-container">
      <a href="#lp-top">
        <div class="arrow-up">
          <%= image_tag "chevron-up-solid.svg", alt: "Back-to-top" %>
        </div>
      </a>

      <div class="back-to-top">
        <p>Back to Top</p>
      </div>
    </div>
  </section>

</div>

<!-- TYPING-EFFECT -->
<script>
  var typeString = ['Educate.  ', 'Grow.  ', 'Engage.  '];
  var  i = 0;
  var count = 0
  var selectedText = '';
  var text = '';
  (function type() {
    if (count == typeString.length) {
      count = 0;
    }
    selectedText = typeString[count];
    text = selectedText.slice(0, ++i);
    document.getElementById('typing').innerHTML = text;
    if (text.length === selectedText.length) {
      count++;
      i = 0;
    }
    setTimeout(type, 400);
  }());

  function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
      }
    }
  }
</script>

app/views/pages/library.html.erb
<div class="primary-container-newsfeed">
  <div class="mx-3 my-4 py-5">
    <br>
      <div class="search-form">
        <div class="search-form-input">
          <%= form_tag library_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Try 'Bitcoin'"
            %>
        </div>
        <div class="search-form-submit">
          <%= submit_tag "Search", class: "btn-gradient" %>
          <% end %>
        </div>
      </div>

    <br>
    <br>
    <br>
    <h5>News, Updates, and Fun Stuff 📰 🙌 </h5>
    <br>
    <% if @own_contents.empty? %>
      <div class="py-2">
        <p>🤓 Oops! We don't have that just yet, try something else.</p>
      </div>
    <% else %>
      <% @own_contents.each do |own_content| %>
        <%= link_to own_content_path(own_content) do %>
          <%= render 'components/card', own_content: own_content %>
          <br>
        <% end %>
      <% end %>
    <% end %>

    <br>
    <br>
    <br>
    <br>
    <h5>Learning Units 📚 🙇</h5>
    <br>
    <% if @education_contents.empty? %>
      <div class="py-2">
        <p>🤓 Oops! We don't have that just yet, try something else.</p>
      </div>
    <% else %>
      <div class="cardsGrid">
        <% @education_contents.each do |edu_content| %>
          <%= link_to education_content_path(edu_content) do %>
            <%= render 'components/cardGrid', edu_content: edu_content %>
            <br>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr></hr>
</div>

app/views/pages/newsfeed.html.erb
<div class="primary-container-newsfeed">
  <div class="m-3 pt-5">

    <br>
    <script src="https://widgets.coingecko.com/coingecko-coin-price-marquee-widget.js"></script>
    <coingecko-coin-price-marquee-widget  coin-ids="bitcoin,ethereum,litecoin,ripple,cardano" currency="usd" background-color="#ffffff" locale="en"></coingecko-coin-price-marquee-widget>
    <br>
    <hr></hr>

    <% if user_signed_in? %>
      <h5><%= current_user.first_name %>, here is your bit-size news 💸</h5>
    <% else %>
      <h5>Hey there, here is your bit-size news 💸</h5>
    <% end %>
    <br>
  </div>

  <div class="cardsnf m-3">
   <!--  <br>
    <p> News from <strong><%= @week_date.strftime("%B %d, %Y")  %></strong> to <strong> <%= Date.today().strftime("%B %d, %Y") %> </strong> </p>
    <br> -->
    <% if @today_content.empty? %>
        <div class="py-2">
          <p>Apologies, our newspaper boy is on his way to deliver the latest news from the crypto world!</p>
        </div>
    <% else %>
      <% @today_content.each do |own_content| %>
        <%= link_to own_content_path(own_content) do %>
          <%= render 'components/card', own_content: own_content %>
          <br>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <hr></hr>



    <!-- Podcast / SPOTIFY -->
    <div class="m-3">
      <h5>Podcasts 🎧</h5>
      <iframe class="spotify-player" src="https://open.spotify.com/embed-podcast/episode/2AAHfZOJWLv0yTeK4mue04" width="100%" height="100%" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      <iframe class="spotify-player" src="https://open.spotify.com/embed-podcast/episode/7z5oMLZ1p6Vg6LhRmk3KWa" width="100%" height="100%" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      <iframe class="spotify-player" src="https://open.spotify.com/embed-podcast/episode/14D71GE6uP9kluB5K0r5DW" width="100%" height="100%" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        <div class= "py-2 d-flex justify-content-between">
          <%= link_to "More Episodes...", favourites_path %>
        </div>
      </div>
    <hr></hr>



    <!-- Education content -->

    <div class="m-3">
      <div class= "py-2 d-flex justify-content-between">
        <h5>Learn 📚</h5>
        <% if user_signed_in? && current_user.admin %>
            <%= link_to "Add", new_education_content_path %>
          <% end %>
      </div>

     <div class="cardsGrid">
        <% if @education_contents.empty? %>
        <div class="py-2">
          <p>Apologies, our teacher is on the way to deliver the latest course from the crypto world!</p>
        </div>
    <% else %>
      <% @top_edu_content.each do |edu_content| %>
        <%= link_to education_content_path(edu_content) do %>
          <%= render 'components/cardGrid', edu_content: edu_content %>
          <br>
        <% end %>
      <% end %>
    <% end %>
    </div>
    <%= link_to "More Education..", library_path %>
  </div>
  <hr></hr>



  <div class='twitterDyk'>
    <!-- Did-you know section -->
    <div class="m-3 didyk">
      <div class= "py-2 d-flex justify-content-between">
        <h5>Did you know? 🤔</h5>
        <% if user_signed_in? && current_user.admin %>
            <%= link_to "Add", new_didyouknow_path %>
          <% end %>
      </div>

    <% if @didyouknows.empty? %>
        <p>Apologies, our minions are currently working really hard to get the latest content to you!</p>


  <!-- Carousel attempt using bootstrap -->

      <% else %>
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= render 'components/thirdpartycard', did_you_know: @didyouknows.first  %>
          </div>
          <% @didyouknows.each_with_index do |dyk_slide, i| %>
              <% if i > 0 %>
                <div class="carousel-item">
                 <%= render 'components/thirdpartycard', did_you_know: dyk_slide %>
                </div>
              <% end %>
          <% end %>
        </div>

        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <% end %>
    </div>

  <!-- end of did you know -->
  <hr></hr>

<!-- start of the twitter feed -->
    <div class="m-3 py-2 twitter">
      <h5>FinTweets 📬</h5>
      <a class="twitter-timeline" data-width="100%" data-height="550" href="https://twitter.com/finmates_co?ref_src=twsrc%5Etfw"></a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  <!-- end of twitter feed -->
 </div>
</div>